name: fdlvrs
favicon: null
layout_spectrum: 0.10804607346653938
typography_spectrum: 0.19597375206649303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6bfa0'
    - '#271f14'
    - '#934835'
    - '#cc7e4e'
    - '#692017'
  brandStrength: 0.9648631671443582
  lightness: 0.9232948950957507
  saturation: 0.6215139306150377
  rhythmicContrast: 0.03178079309873283
purpose: []
